version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:${PHP_VERSION}
    working_dir: /var/www/html
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html # Non Mac users.
      - ~/.composer/cache:/root/.composer/cache
      - ~/.drush/cache:/root/.drush/cache
      # - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
    depends_on:
      - mysql

    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254 remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      # VIRTUAL_HOST: platform-dev
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1
  mysql:
    image: percona/percona-server:${MYSQL_VERSION}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  # Spawn a Selenium server which also includes a VNC server on localhost:5900 (the password is "secret")
  selenium:
    image: selenium/standalone-chrome-debug:${SELENIUM_CHROME}
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - VNC_NO_PASSWORD=1
    ports:
      - "5900:5900"
    expose:
      - '4444'
